[output]
    format = "colored-line-number"
[errcheck]
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions = true
[linters]
    enable = [
        "asciicheck",
        "dogsled",
        "gocognit",
        "goconst",
        "gocyclo",
        "gocritic",
        "godot",
        "godox",
        "goerr113",
        "gofmt",
        "gomnd",
        "gosec",
        "interfacer",
        "lll",
        "maligned",
        "unconvert",
        "unparam",
    ]

[linters-settings.gocritic]
    disabled-checks = [ "ifElseChain" ]

[issues]
    exclude-rules = [
        { path = "_test.go", linters = [ "goconst", "lll" ] },
        { source = "^//.*noinspection", linters = [ "godot" ] }
    ]